---
exp_name: TRN
exp_dir: exp/TRN
runner: TrnRunner
use_gpu: true
device: cuda:0
gpus: [0]
seed: 1234
dataset:
  loader_name: TrnDataset
  dataset_name: Julia
  data_path: data/julia
  source: local
  node_order: [lex_topological] # topological/lex_topological/all
  train_ratio: 0.8
  dev_ratio: 0.2
  num_subgraph_batch: 1 # number of subgraphs per mini-batch
  num_fwd_pass: 1
  is_save_split: false  
  is_sample_subgraph: true # set to true if you want to sample subgraphs
  is_overwrite_precompute: true
  dataset_min_num_nodes: 10
  dataset_max_num_nodes: 1000
  is_tril: true
model:
  model_name: TrnModel
  is_sym: false
  hidden_dim: 512
  embedding_dim: 512
  att_edge_dim: 64
  num_GNN_layers: 7
  num_GNN_prop: 1
  num_canonical_order: 1
  has_attention: true
  edge_weight: 1.0e+0
  node_dist_feat_dim: 128
train:
  optimizer: Adam
  lr_decay: 0.1
  lr_decay_epoch: [5000, 10000, 15000, 20000, 25000, 30000,35000] 
  num_workers: 25
  max_epoch: 1001
  batch_size: 16
  display_iter: 400
  snapshot_epoch: 100
  valid_epoch: 50
  lr: 1.0e-3
  wd: 0.0e-4
  momentum: 0.75
  shuffle: true
  is_resume: false
  resume_epoch: #1
  resume_dir: #./exp/TRN/TrnModel_Julia_2020-Jul-08-19-30-48_31152
  resume_model: #model_snapshot_0000100.pth
test:  
  batch_size: 16
  num_test_gen: 160
  is_vis: true
  is_single_plot: false # visualize `num_vis` samples in a single image
  num_vis: 20
  vis_num_row: 5 # visualize `num_vis` samples in `vis_num_row` rows
  test_model_dir: ./exp/TRN/TrnModel_Julia_2020-Jul-09-09-10-46_14698
  test_model_name: model_snapshot_0000100.pth
  init_tree: true #initialize generative graph with directory and one node
